Profile name needs to be not false for first time users.
org.hibernate.PropertyValueException: not-null property references a null or transient value: nz.co.searchwellington.model.UserImpl.profilename
	org.hibernate.engine.Nullability.checkNullability(Nullability.java:95)